import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import userRouter from "./user";
import walletsRouter from "./wallets";
import transactionsRouter from "./transactions";
import ratesRouter from "./rates";
import countriesRouter from "./countries";
import paymentMethodsRouter from "./payment-methods";
import depositsRouter from "./deposits";
import withdrawalsRouter from "./withdrawals";
import adminRouter from "./admin";
import ticketsRouter from "./tickets";
import settingsRouter from "./settings";
import streamRouter from "./stream";
import contactsRouter from "./contacts";
import kycRouter from "./kyc";
import profileRouter from "./profile";
import cryptoRouter from "./crypto";
import cryptoDepositsRouter from "./crypto-deposits";
import wallpapersRouter from "./wallpapers";
import pushRouter from "./push";
import agoraRouter from "./agora";
import p2pRouter from "./p2p";
import escrowRouter from "./escrow";
import paidCallsRouter from "./paid-calls";
import translatorRouter from "./translator";
import liveServicesRouter from "./live-services";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(userRouter);
router.use(walletsRouter);
router.use(transactionsRouter);
router.use(ratesRouter);
router.use(countriesRouter);
router.use(paymentMethodsRouter);
router.use(depositsRouter);
router.use(withdrawalsRouter);
router.use(adminRouter);
router.use(ticketsRouter);
router.use(settingsRouter);
router.use(streamRouter);
router.use(contactsRouter);
router.use(kycRouter);
router.use(profileRouter);
router.use(cryptoRouter);
router.use(cryptoDepositsRouter);
router.use(wallpapersRouter);
router.use(pushRouter);
router.use(agoraRouter);
router.use(p2pRouter);
router.use(escrowRouter);
router.use(paidCallsRouter);
router.use('/translator', translatorRouter);
router.use(liveServicesRouter);

export default router;
